USE ATIVIDADE_1;
CREATE TABLE TB_PAIS (
ID_PAIS INT NOT NULL AUTO_INCREMENT, 
  NM_PAIS VARCHAR(200),  
  NR_POPULACAO NUMERIC(10),
  PRIMARY KEY (ID_PAIS)
);
CREATE TABLE TB_CIRCUITO ( 
  ID_CIRCUITO INT NOT NULL AUTO_INCREMENT, 
  NM_CIRCUITO VARCHAR(200), 
  NR_EXTENSAO NUMERIC(10), 
  ID_PAIS INT,
  PRIMARY KEY (ID_CIRCUITO),
  FOREIGN KEY(ID_PAIS) REFERENCES TB_PAIS (ID_PAIS) 
);
CREATE TABLE TB_PROVA ( 
  ID_PROVA INT NOT NULL AUTO_INCREMENT, 
  DT_PROVA DATE, 
  NM_SITUACAO VARCHAR(200), 
  ID_CIRCUITO INT, 
  PRIMARY KEY (ID_PROVA),
  FOREIGN KEY(ID_CIRCUITO) REFERENCES TB_CIRCUITO (ID_CIRCUITO) 
);
CREATE TABLE TB_EQUIPE ( 
  ID_PROVA INT NOT NULL AUTO_INCREMENT, 
  NM_EQUIPE VARCHAR(200), 
  ID_PAIS INT,
  PRIMARY KEY (ID_PROVA),
  FOREIGN KEY(ID_PAIS) REFERENCES TB_PAIS(ID_PAIS) 
);
CREATE TABLE TB_PILOTO (  
  ID_PILOTO INT NOT NULL AUTO_INCREMENT, 
  NM_PILOTO VARCHAR(200) NOT NULL, 
  DT_NASCIMENTO DATE, 
  ID_PAIS INT,
  ID_EQUIPE INT, 
  PRIMARY KEY (ID_PILOTO),
  FOREIGN KEY(ID_PAIS) REFERENCES TB_PAIS(ID_PAIS), 
  FOREIGN KEY(ID_EQUIPE) REFERENCES TB_EQUIPE(ID_EQUIPE) 
);
CREATE TABLE TB_RESULTADO ( 
  ID_PROVA INT, 
  ID_PILOTO INT,
  FOREIGN KEY (ID_PROVA) REFERENCES TB_PROVA(ID_PROVA), 
  FOREIGN KEY (ID_PILOTO) REFERENCES TB_PILOTO(ID_PILOTO), 
  PRIMARY KEY (ID_PROVA, ID_PILOTO), 
  NR_TEMPO_DE_PROVA TIME(4), 
  NR_COLOCAO_FINAL NUMERIC(3), 
  NR_POSICAO_GRID NUMERIC(3), 
  NR_MELHOR_VOLTA NUMERIC(3) 
);